### ISSUE TITLE
Set Text color and font?

### ISSUE THREAD

**Issue by alelordelo** [canopas/rich-editor-swiftui#43]
Hello guys, thanks for sharing this!

I am currently using rich text editor by Daniel Sadi, but looking for a simpler version that I can customise.

Do you guys plan to support setting Text color and font?

**Comment by cp-divyesh-v** [comment]
@alelordelo Yes, we can't promise a specific date, but it is on our roadmap. We are working towards creating a RichEditor similar to [FlutterQuill](https://pub.dev/packages/flutter_quill) for both platform iOS and [Android](https://github.com/canopas/rich-editor-compose)

**Comment by alelordelo** [comment]
@cp-divyesh-v great goal! : )

Will have a look and see if I can contribute with text colors

**Comment by cp-divyesh-v** [comment]
@alelordelo Now we are supporting font color, and we'll add font customization soon.

**Comment by alelordelo** [comment]
nice! did you guys merge my MacOS code?

**Comment by cp-divyesh-v** [comment]
@alelordelo Closing this as this is now supported.
