### ISSUE TITLE
MacOS version has been ported

### ISSUE THREAD

**Issue by alelordelo** [canopas/rich-editor-swiftui#44]
Hello Canopas team,

I ported the code to MacOS/Appkit over the weekend, project is on the zip bellow:
[rich-editor-swiftui-main-3.zip](https://github.com/user-attachments/files/16494714/rich-editor-swiftui-main-3.zip)

<img width="1440" alt="Screenshot 2024-08-05 at 13 02 13" src="https://github.com/user-attachments/assets/f09e59ef-4f9d-4de5-acdb-deacfc89859b">

On this code:
```
import Foundation

public class RichEditorState: ObservableObject {
    private var adapter: EditorAdapter = DefaultAdapter()

    @Published internal var editableText: NSMutableAttributedString
```

Xcode prints this, when trying to apply rich text:
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

Then rich text doesn't get applied, and you need to click on underwrite and then it works.

Please let me know what you guys think, and if you could help solve this issue.

Next steps would be.

1. undo manager
2. Color
3. Font

Cheers

**Comment by Faolain** [comment]
Nice work, can you create a PR @alelordelo ?

**Comment by alelordelo** [comment]
Not sure how to do PRs with projects that have local SPM packages….

but you can open the zip and push I guess?

**Comment by cp-divyesh-v** [comment]
We have ported macOS and other platforms as well with last PR
