### ISSUE TITLE
Suggestions for Updating the README

### ISSUE THREAD

**Issue by Yipxiyi** [canopas/rich-editor-swiftui#54]
I really like this clean and minimalistic rich text editor, but it seems that some RichTextAction function (such as stepIndent and bullet) are not functioning properly. It would be great to update the README to reflect the currently supported features. 

Additionally, I noticed in the changelog that list styles are now supported, but it seems they cannot yet be applied using toggleStyle?

**Comment by cp-divyesh-v** [comment]
@Yipxiyi Thanks for giving time and attention to detail
But, I am not finding anything that say we support Bullet list or any other list style in our latest read.me and we less prioritised that support as it was taking too much time and still it's not fully functional, we tried and supported only single indent list I mean plain single list, but we prioritised other things over it.

**Comment by Yipxiyi** [comment]
> @Yipxiyi Thanks for giving time and attention to detail But, I am not finding anything that say we support Bullet list or any other list style in our latest read.me and we less prioritised that support as it was taking too much time and still it's not fully functional, we tried and supported only single indent list I mean plain single list, but we prioritised other things over it. And rollback that support as it was not fully functional.

Totally understand. Thank you very much for your reply and very much looking forward to the subsequent updates! I will close this issue.
